{{- if .Values.webhook.enabled && .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.webhook.certManager.certificateName }}
  namespace: {{ include "aws-global-accelerator-controller.namespace" . }}
spec:
  dnsNames:
  - {{ .Values.webhook.serviceName }}.{{ include "aws-global-accelerator-controller.namespace" . }}.svc
  - {{ .Values.webhook.serviceName }}.{{ include "aws-global-accelerator-controller.namespace" . }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Values.webhook.certManager.issuerName }}
  secretName: {{ .Values.webhook.certManager.certificateSecretName }}
{{- end -}}
