{{- if .Values.webhook.enabled && .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.webhook.certManager.issuerName }}
  namespace: {{ include "aws-global-accelerator-controller.namespace" . }}
spec:
  selfSigned: {}
{{- end -}}
