{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodemanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnoderefreshers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnoderefreshers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodereplenishers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - awsnodereplenishers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - nodemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.h3poteto.dev
  resources:
  - nodemanagers/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
